language: python
python:
  - "2.7"
  - "3.4"
  - pypy
# command to install dependencies, 
install:
    - pip install -vr requirements.txt||true
# command to run tests, e.g. python setup.py test
script:
  - echo $TRAVIS_PYTHON_VERSION
  - cd .. && supybot-test UrbanDictionary
notifications:
    email: false
    irc:
      channels:
        - "irc.efnet.net#supybot"
      template:
        - "Build #%{build_number}: %{repository} %{branch} (%{commit}) %{author} - %{message}"
        - "Build details: \x03 %{build_url}"
matrix:
    fast_finish: true

