language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
# command to install dependencies, 
install:
  - pip install -vr requirements.txt||true
# command to run tests, e.g. python setup.py test
script:
  - echo $TRAVIS_PYTHON_VERSION
  - cd .. && supybot-test WolframAlpha
notifications:
  email: false
  irc: "irc.efnet.net#supybot"
  webhooks: http://n.tkte.ch/h/3527/rm2ycnsYzBtH8Qqg2AAmqjTM
matrix:
  fast_finish: true
