sudo: false
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - pypy
  - pypy3
# command to install dependencies, 
install:
    - pip install -vr requirements.txt
# command to run tests, e.g. python setup.py test
script:
  - cd .. && mv Supybot-Weather Weather
  - supybot-test Weather
notifications:
    email: false
matrix:
    fast_finish: true
    allow_failures:
        - python: "pypy"
        - python: "pypy3"
